### ISSUE TITLE
cant get it to hide `assets` folder

### ISSUE THREAD

**Issue by zeltak** [ptrsvltns/hidden-folder-obsidian#11]
Hi and thx for this great plugin!

I tried using it with a simple regex to hide the `assets` folder  across the whole vault but that never seems to work (see image below)

any clue what im doing wrong?

![CleanShot 2022-12-19 at 12 59 21](https://user-images.githubusercontent.com/498410/208411261-f9756d48-41c3-498b-8ba3-01cdc59b1aba.png)

best

Z

**Comment by ptrsvltns** [comment]
The regular match is the full path, the full path to your subfolder is `101 Lib/assets`
Try this `\/?assets$`

**Comment by zeltak** [comment]
Perfect!!!

thx so much for your amazing work, really appreciated!

Z
