### ISSUE TITLE
Why not File Hider plugin?

### ISSUE THREAD

**Issue by papatistos** [ptrsvltns/hidden-folder-obsidian#13]
I like the simplicity of the plugin but I wonder what kept you from using the [File Hider plugin](https://github.com/Oliver-Akins/file-hider). Could you briefly clarify so people have some guidance when deciding which plugin to install?

**Comment by ptrsvltns** [comment]
I didn't find any relevant plugins before making my own. Thank you very much for sharing the plugin [File Hider](https://github.com/Oliver-Akins/file-hider). I will use it too.
