### ISSUE TITLE
How to use RegEx for Multiple Folders?

### ISSUE THREAD

**Issue by julroger2013** [ptrsvltns/hidden-folder-obsidian#2]
Thank you for creating this plugin! I tried using RegEx to select folders to hide. 

The two folders I'm trying to hide are "zzz Trash" and "zzz notion-like-tables"

Using the Regex ^zzz Trash$ or ^zzz notion-like-tables$ I was able to hide one folder or the other, but not both. What sort of RegEx would I need to use to hide both folders at once?

**Comment by ptrsvltns** [comment]
@julroger2013 
Thank you for submitting a bug!

I've fixed the issue of multiple folders not taking effect.

I made new demo gifs tutorial

RELEASE 1.0.2 #3
