### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by wuzhen97** [ptrsvltns/hidden-folder-obsidian#7]
![image](https://user-images.githubusercontent.com/61906420/207515496-599a6c58-7c1c-4916-8b1e-79e57d36ad6b.png)

**Comment by ptrsvltns** [comment]
> ![image](https://user-images.githubusercontent.com/61906420/207515496-599a6c58-7c1c-4916-8b1e-79e57d36ad6b.png)

Fixed, look at [1.0.6](https://github.com/ptrsvltns/hidden-folder-obsidian/releases/tag/1.0.6)
